namespace Stensones.GD92.Fields;

public enum StatusCodeValue : byte
{
	NoStatusData = 0,
	MobileToIncident = 1,
	InAttendanceAtIncident = 2,
	AvailableAtIncident = 3,
	AvailableAtBase = 4,
	NotAvailable = 5,
	AvailableContactByRadio = 6,
	AvailableHomeAddress = 7,
	AvailableGuesting = 8,
	AvailablePager = 9,
	MobileToStandbyLocation = 10,
	AvailableByTelephone = 11,
	IncidentClosed = 12,
	Stop = 13,
	MobileUnavailable = 14,
	DefectiveUnavailable = 15,
	InsufficientCrewAvailable = 16,
	AvailableOtherTelephone = 17,
	OutOfArea = 18,
	Pending = 19,
	AvailableDelayedTurnout = 20,
	NextMessage = 21,
	KeepInformed = 22,
	RedirectToAnotherIncident = 23,
	MobileInStandbyStationsArea = 24,
	AtStandbyStation = 25,
	MobileToGuestAtAnotherStation = 26,
	MobileGuestingInAnotherStationsArea = 27,
	DelayedResponseOffStation = 28,
	MobileReturnToStationIfRequired = 29,
	MobileDepletedCrew = 30,
	MobileBreathingApparatusDeficiency = 31,
	AvailableAlerter = 32,
	OnDutyNotAvailable = 33,
	AvailableBaseOfficer = 34,
	MobileAvailable = 35,
	AvailableMobileToBase = 36,
	OffDuty = 37,
	Batched = 38
}
