<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" />
    <PackageReference Include="WolverineFx.RabbitMQ" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fields\Stensones.GD92.Fields.csproj" />
    <ProjectReference Include="..\GD92.StationEnd.ServiceDefaults\GD92.StationEnd.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Messages\Stensones.GD92.Messages.csproj" />
    <ProjectReference Include="..\NodeManager.Persistence\NodeManager.Persistence.csproj" />
    <ProjectReference Include="..\ParticipantParameters\ParticipantParameters.csproj" />
    <ProjectReference Include="..\Transport.RabbitMQ\Stensones.GD92.Transport.RabbitMQ.csproj" />
  </ItemGroup>

</Project>
