// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrinterUA.Persistence;

#nullable disable

namespace PrinterUA.Persistence.Migrations
{
    [DbContext(typeof(PrinterUaDbContext))]
    [Migration("20260912194216_InitialPrinterUaParameterPersistence")]
    partial class InitialPrinterUaParameterPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("node")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrinterUA.Persistence.ParameterSetRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("Kind")
                        .HasColumnType("smallint");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Kind")
                        .IsUnique();

                    b.ToTable("parameter_set", "node");
                });

            modelBuilder.Entity("PrinterUA.Persistence.PersistedParameterValueRecord", b =>
                {
                    b.Property<Guid>("ParameterSetId")
                        .HasColumnType("uuid");

                    b.Property<byte>("ParameterNumber")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("EncodedValue")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("ParameterSetId", "ParameterNumber");

                    b.ToTable("parameter_value", "node");
                });

            modelBuilder.Entity("PrinterUA.Persistence.PersistedParameterValueRecord", b =>
                {
                    b.HasOne("PrinterUA.Persistence.ParameterSetRecord", null)
                        .WithMany()
                        .HasForeignKey("ParameterSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
