// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Router.Persistence;

#nullable disable

namespace Router.Persistence.Migrations
{
    [DbContext(typeof(RouterDbContext))]
    [Migration("20260907183957_EnsureSingleRouterManagedEntity")]
    partial class EnsureSingleRouterManagedEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("node")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Router.Persistence.CommunicationsNodeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("communications_node", "node");
                });

            modelBuilder.Entity("Router.Persistence.ManagedEntityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("Kind")
                        .HasColumnType("smallint");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Kind")
                        .IsUnique();

                    b.HasIndex("NodeId", "Kind")
                        .IsUnique();

                    b.ToTable("managed_entity", "node");
                });

            modelBuilder.Entity("Router.Persistence.ParameterSetRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("Kind")
                        .HasColumnType("smallint");

                    b.Property<Guid>("ManagedEntityId")
                        .HasColumnType("uuid");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ManagedEntityId", "Kind")
                        .IsUnique();

                    b.ToTable("parameter_set", "node");
                });

            modelBuilder.Entity("Router.Persistence.PasswordVerifierRecord", b =>
                {
                    b.Property<Guid>("ParameterSetId")
                        .HasColumnType("uuid");

                    b.Property<byte>("ParameterNumber")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<int>("WorkFactor")
                        .HasColumnType("integer");

                    b.HasKey("ParameterSetId", "ParameterNumber");

                    b.ToTable("password_verifier", "security", t =>
                        {
                            t.HasCheckConstraint("CK_password_verifier_ParameterNumber", "\"ParameterNumber\" = 5");
                        });
                });

            modelBuilder.Entity("Router.Persistence.PersistedParameterValueRecord", b =>
                {
                    b.Property<Guid>("ParameterSetId")
                        .HasColumnType("uuid");

                    b.Property<byte>("ParameterNumber")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("EncodedValue")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("ParameterSetId", "ParameterNumber");

                    b.ToTable("parameter_value", "node");
                });

            modelBuilder.Entity("Router.Persistence.ManagedEntityRecord", b =>
                {
                    b.HasOne("Router.Persistence.CommunicationsNodeRecord", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Router.Persistence.ParameterSetRecord", b =>
                {
                    b.HasOne("Router.Persistence.ManagedEntityRecord", null)
                        .WithMany()
                        .HasForeignKey("ManagedEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Router.Persistence.PasswordVerifierRecord", b =>
                {
                    b.HasOne("Router.Persistence.ParameterSetRecord", null)
                        .WithMany()
                        .HasForeignKey("ParameterSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Router.Persistence.PersistedParameterValueRecord", b =>
                {
                    b.HasOne("Router.Persistence.ParameterSetRecord", null)
                        .WithMany()
                        .HasForeignKey("ParameterSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
