// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace NodeManager.Persistence.Migrations;

[DbContext(typeof(NodeManagerDbContext))]
partial class NodeManagerDbContextModelSnapshot : ModelSnapshot
{
	protected override void BuildModel(ModelBuilder modelBuilder)
	{
#pragma warning disable 612, 618
		modelBuilder
			.HasDefaultSchema("node")
			.HasAnnotation("ProductVersion", "10.0.11")
			.HasAnnotation("Relational:MaxIdentifierLength", 63);

		NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

		modelBuilder.Entity("NodeManager.Persistence.ParameterSetRecord", entity =>
		{
			entity.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
			entity.Property<byte>("Kind").HasColumnType("smallint");
			entity.Property<long>("Revision").IsConcurrencyToken().HasColumnType("bigint");
			entity.HasKey("Id");
			entity.HasIndex("Kind").IsUnique();
			entity.ToTable("parameter_set", "node");
		});

		modelBuilder.Entity("NodeManager.Persistence.PersistedParameterValueRecord", entity =>
		{
			entity.Property<Guid>("ParameterSetId").HasColumnType("uuid");
			entity.Property<byte>("ParameterNumber").HasColumnType("smallint");
			entity.Property<byte[]>("EncodedValue").IsRequired().HasColumnType("bytea");
			entity.HasKey("ParameterSetId", "ParameterNumber");
			entity.ToTable("parameter_value", "node");
		});

		modelBuilder.Entity("NodeManager.Persistence.PersistedParameterValueRecord", entity =>
		{
			entity.HasOne("NodeManager.Persistence.ParameterSetRecord", null)
				.WithMany()
				.HasForeignKey("ParameterSetId")
				.OnDelete(DeleteBehavior.Cascade)
				.IsRequired();
		});
#pragma warning restore 612, 618
	}
}
