namespace Stensones.GD92.Fields;

public enum GD92MessageType : byte
{
	MobiliseCommand = 1,
	MobiliseMessage = 2,
	PageOfficer = 3,
	AreaPageMessage = 4,
	ResourceStatusRequest = 5,
	PrimaryRadioMobiliseMessage = 6,
	ActivatePeripheral = 7,
	DeactivatePeripheral = 8,
	PeripheralStatusRequest = 9,
	ResetRequest = 10,
	ResourceStatus = 20,
	DutyStaffingUpdate = 21,
	LogUpdate = 22,
	Stop = 23,
	MakeUp = 24,
	InterruptRequest = 25,
	Text = 27,
	PeripheralStatus = 28,
	Reset = 30,
	IncidentNotification = 31,
	AlertCrew = 40,
	AlertStatus = 42,
	AlertEng = 43,
	Acknowledgement = 50,
	NegativeAcknowledgement = 51,
	SetParameter = 60,
	ParameterRequest = 61,
	Parameter = 62,
	ParameterRequestMultiple = 63,
	Test = 64,
	PrinterStatus = 65,
	MtaStatusChange = 66,
	RouteStatus = 67,
	SupplierMessage = 100,
	BrigadeMessage = 101,
	DatabaseQuery = 102,
	FormattedText = 103,
	ProformaDefinitionQuery = 104,
	ProformaDefinition = 105
}
